name: {{{app_package_name}}}
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # architecture
  bloc: 8.1.1
  flutter_bloc: 8.1.2

  # dependency injection
  get_it: 7.4.0

  # functional programming, used for Either type
  dartz: 0.10.1

  # equality checks
  equatable: 2.0.5

  # localization
  intl: 0.17.0

  # widgets
  gap: 3.0.0

  # logging
  logger: 1.3.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  # code analysis
  lint: 2.0.1
  dart_code_metrics: 5.7.2
  custom_lint: 0.3.4
  clean_architecture_lints:
    path: tools/custom_lints/clean_architecture_lints

  # tests
  golden_toolkit: 0.15.0
  alchemist: 0.6.0
  mocktail_image_network: 0.3.1
  mocktail: 0.3.0
  bloc_test: 9.1.1
  import_sorter: 4.6.0

  # utils
  meta: 1.8.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/
    - assets/images/

flutter_gen:
  output: lib/resources/
  line_length: 120

flutter_intl:
  enabled: true
import_sorter:
  emojis: false # Optional, defaults to false
  comments: false # Optional, defaults to true
  ignored_files: # Optional, defaults to []
    - \/lib\/*